# Generated by Django 4.2 on 2023-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_interest_profile_orientation_profile_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(blank=True, choices=[('H', 'Heterosexual'), ('HO', 'Homosexual'), ('B', 'Bisexual'), ('P', 'Pansexual'), ('A', 'Asexual'), ('O', 'Otro')], max_length=2),
        ),
    ]
