# Generated by Django 4.2 on 2023-06-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Heterosexual', 'Heterosexual'), ('Homosexual', 'Homosexual'), ('Bisexual', 'Bisexual'), ('Pansexual', 'Pansexual'), ('Asexual', 'Asexual'), ('Otro', 'Otro')], max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=6),
        ),
    ]
