# Generated by Django 4.2 on 2023-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='default-placeholder.png', null=True, upload_to='fotos_perfil_folder'),
        ),
    ]
