# Generated by Django 4.2 on 2023-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_options',
            field=models.CharField(blank=True, default='Intereses', max_length=50, null=True),
        ),
    ]
