# Generated by Django 4.2 on 2023-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='search_options',
            field=models.CharField(blank=True, default='Intereses', max_length=50, null=True),
        ),
    ]
