# Generated by Django 4.2 on 2023-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_search_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='default-placeholder.png', max_length=200, null=True, upload_to='fotos_perfil_folder'),
        ),
    ]
