# Generated by Django 4.2 on 2023-06-05 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateTimeField()),
                ('registered_users', models.ManyToManyField(related_name='registered_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
