# Generated by Django 4.2 on 2023-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_registered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default-placeholder.png', null=True, upload_to='fotos_evento_folder'),
        ),
    ]
