# Generated by Django 4.2 on 2023-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
